### ISSUE TITLE
Displays not working

### ISSUE THREAD

**Issue by jkronen** [AverageMaker/ZeroSeg#6]
Hello,

I just solderd my ZeroSeg but I can't get the displays working. The button_example.py is working without any problems, but the displays stay dark at every example.

When I powered my Pi I had another script in my autostart (one for adressing a christmas tree (randomly powering the GPIOs)) which made some of the Segements light up. So I don't think it is any soldering problem.

When running the examples there are no errors displayed.

Thank you for any help!

**Comment by mszyszko** [comment]
I think I had exactly the same problem. It seems that the ZeroSeg is not fully compatible with the newest raspberry firmware. I fixed the problem by _downgrading_ the raspberry firmware. 

I used _rpi-update_ (https://github.com/Hexxeh/rpi-update) and dowgraded to commit "330fb17cb87c2b57cf8e670b34b7a27527b787fa" (see: https://github.com/Hexxeh/rpi-firmware/commit/330fb17cb87c2b57cf8e670b34b7a27527b787fa)

like so:

`sudo rpi-update 330fb17cb87c2b57cf8e670b34b7a27527b787fa`

I didn't test all the versions - maybe there is a newer version for which the problem does not occur.

Be advised: This "fix" is not a great solution to the problem - do it at your own risk.

**Comment by 2jmike** [comment]
Yes...From what i can gather, the raspbian-jessie OS from 2017-07-05 is the one to use as the newest raspbian version contains a bug which prevents zeroseg from operating.

**Comment by markdootson** [comment]
The fix for current code. Don't use xfer2 ( there's no return data ) and specify a speed the target IC can cope with:

self._spi.xfer(list(data), 5000000)

This works for me and 'should work regardless of changing default speeds in the Kernel - or whatever causes this. The chip datasheet says 10Mhz max - which also works for me but I thought 5Mhz would be fine.

**Comment by Radiocode1969** [comment]
I can confirm that changing:

self._spi.xfer2(list(data)) 
to 
self._spi.xfer(list(data), 5000000) 

in /ZeroSeg/build/lib.linux.armv6l-2.7/ZeroSeg/led.py (and re-running the install/build script) does indeed work on a raspberry Pi Zero with the latest Raspian (2018-06-27-raspbian-stretch-lite).

Thank you @markdootson

**Comment by AverageMaker** [comment]
> The fix for current code. Don't use xfer2 ( there's no return data ) and specify a speed the target IC can cope with:
> 
> self._spi.xfer(list(data), 5000000)
> 
> This works for me and 'should work regardless of changing default speeds in the Kernel - or whatever causes this. The chip datasheet says 10Mhz max - which also works for me but I thought 5Mhz would be fine.

Thank you for the fix advice. I have updated the repo with this fix.

**Comment by Radiocode1969** [comment]
Hi,

You’re welcome.

Regards,

Lee
