### ISSUE TITLE
 "No module named ZeroSeg"

### ISSUE THREAD

**Issue by KanyQan** [AverageMaker/ZeroSeg#7]
This is what happens when I'm trying to run one of the scripts from examples folder.
Actually i need ANY information about that issue. I don't know if ZeroSeg has been soldered correctly. I don't know anything, Is there ANY way to test ZeroSeg ?

**Comment by KanyQan** [comment]
Error was all about newest version of Raspberry Pi, that is bugged. Do fix this please install 2017-07-05-raspbian-jessie.

**Comment by AverageMaker** [comment]
Sounds like you might be trying to run this in Python 3. This library only works with Python2 just now, however I'm looking at how to make it work with Python3. Are you trying to run the commands in Python3 i.e. 'sudo python3 zeroseg_example.py'?

Sorry for the delay in replying.

**Comment by AverageMaker** [comment]
> Error was all about newest version of Raspberry Pi, that is bugged. Do fix this please install 2017-07-05-raspbian-jessie.

The error with new versions of Raspbian has been fixed. Also please note that this library should be run with Python2.
