### ISSUE TITLE
All segments illuminated, examples run without error but with no effect.

### ISSUE THREAD

**Issue by sjfheaton** [AverageMaker/ZeroSeg#8]
Have recently assembled a ZeroSeg for use with Pi Zero W. Checked all soldering with magnifying glass and all seems fine. Examples built as per instructions and raspbian configured as required. Upon boot all segments illuminate. Examples run without error but with no effect. Have run SPI loopback code successfully. (wget https://raw.githubusercontent.com/raspberrypi/linux/rpi-3.10.y/Documentation/spi/spidev_test.c).

Any suggestions on further diagnostic procedures please?

**Comment by mszyszko** [comment]
I had exactly the same problem. It seems that the ZeroSeg is not fully compatible with the newest raspberry firmware. I fixed the problem by _downgrading_ the raspberry firmware. 

I used _rpi-update_ (https://github.com/Hexxeh/rpi-update) and dowgraded to commit "330fb17cb87c2b57cf8e670b34b7a27527b787fa" (see: https://github.com/Hexxeh/rpi-firmware/commit/330fb17cb87c2b57cf8e670b34b7a27527b787fa)

like so:

`sudo rpi-update 330fb17cb87c2b57cf8e670b34b7a27527b787fa`

I didn't test all the versions - maybe there is a newer version for which the problem does not occur.

Be advised: This "fix" is not a great solution to the problem - do it at your own risk.

**Comment by rm-hull** [comment]
guys, @AverageManVsPi doesn’t seem to be maintaining this library anymore. 

It was a old port of my max7219 driver, which is currently maintained and now called [luma.led_matrix](https://github.com/rm-hull/luma.led_matrix). The library fully supports zeroseg and other led matrix devices

**Comment by sjfheaton** [comment]
Hi Folks,

Thanks very much for your updates.

Kind regards, Simon
