### ISSUE TITLE
Sorry: TabError: inconsistent use of tabs and spaces in indentation in led.py

### ISSUE THREAD

**Issue by dglaude** [AverageMaker/ZeroSeg#9]
When installing the library with `sudo python3 setup.py install` I get a lot of _Sorry: TabError: inconsistent use of tabs and spaces in indentation_ from led.py.

I don't know if this library is supposed to be Python3 compatible, but a mix of space and tab is never good.

**Comment by AverageMaker** [comment]
Indentation inconsistencies removed in latest update. I'm not sure if this will guarantee Python3 compatibility (something I'll look at) but it's a step in the right direction. Thanks and apologies for the delay.
